### ISSUE TITLE
Query did not match any selection rule

### ISSUE THREAD

**Issue by imperio-wxm** [yanagishima/yanagishima#30]
**yanagishima version**:
11

**presto version**:
0.196

**conf/yanagishima.properties**:
```java
jetty.port=7080
presto.datasources=ua212
presto.coordinator.server.ua212=http://xxxx:7070
catalog.ua212=hive
schema.ua212=default
sql.query.engines=presto
```
**JVM version** (`java -version`):
jdk1.8.0_121

**Browser**:
chrome 65.0.3325.162

**Description of the problem including expected versus actual behavior**:
I start yanagishima and i can see web ui, but when i click TreeView button get error:
There is no db info and  table schemas.
```java
2018/03/21 13:04:19.399 +0800 ERROR [PrestoServlet] [Yanagishima] java.sql.SQLException: Query failed (#20180321_050419_00012_zgwnw) in ua212: Query did not match any selection rule
yanagishima.exception.QueryErrorException: java.sql.SQLException: Query failed (#20180321_050419_00012_zgwnw) in ua212: Query did not match any selection rule
        at yanagishima.service.PrestoServiceImpl.resultsException(PrestoServiceImpl.java:350)
        at yanagishima.service.PrestoServiceImpl.getPrestoQueryResult(PrestoServiceImpl.java:237)
        at yanagishima.service.PrestoServiceImpl.doQuery(PrestoServiceImpl.java:106)
        at yanagishima.servlet.PrestoServlet.lambda$doPost$5(PrestoServlet.java:106)
        at java.util.Optional.ifPresent(Optional.java:159)
        at yanagishima.servlet.PrestoServlet.doPost(PrestoServlet.java:65)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:38)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Query failed (#20180321_050419_00012_zgwnw) in ua212: Query did not match any selection rule
        ... 40 more
Caused by: com.facebook.presto.spi.PrestoException: Query did not match any selection rule
        at com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager.selectGroup(InternalResourceGroupManager.java:285)
        at com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager.submit(InternalResourceGroupManager.java:122)
        at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:489) 
```

**Comment by wyukawa** [comment]
It seems like a presto problem.
```20180321_050419_00012_zgwnw``` is the presto query id.
You can check the error of query through presto web ui(e.g. http://xxxx:7070/query.html?20180321_050419_00012_zgwnw)

**Comment by litaiqing** [comment]
Update YanagishimaConfig.java	
Edit Code:
`public String getUser(String datasource) {`
`    String user = properties.getProperty("user." + datasource);`
`    if (user == null) {`
`        user = "yanagishima";`
`    }`
`    return user;`
`}`

`public String getSource(String datasource) {`
`    String source = properties.getProperty("source." + datasource);`
`    if (source == null) {`
`        source = "yanagishima";`
`    }`
`    return source;`
`}`

Properties:

presto.coordinator.server.ark-presto=http://localhost:8080
presto.redirect.server.ark-presto=http://localhost:8080
catalog.ark-presto=hive
schema.ark-presto=default
**_user.ark-presto=isuhadoop_**
**_source.ark-presto=ark-presto_**

Repair error: Query did not match any selection rule

The modified code has been submitted for merging.

OK!
