### ISSUE TITLE
Unable to connect to TLS secured presto

### ISSUE THREAD

**Issue by datta90** [yanagishima/yanagishima#307]
**yanagishima version*20.0*:

**presto version*prestosql 350*:

**conf/yanagishima.properties**:
```
jetty.port=8085
# 30 minutes. If presto query exceeds this time, yanagishima cancel the query.
presto.query.max-run-time-seconds=1800
# 1GB. If presto query result file size exceeds this value, yanagishima cancel the query.
presto.max-result-file-byte-size=1073741824
# you can specify freely. But you need to specify same name to presto.coordinator.server.[...] and presto.redirect.server.[...] and catalog.[...] and schema.[...]
presto.datasources=your-presto
auth.your-presto=true
# presto coordinator url
presto.coordinator.server.your-presto=https://srdcb0001gpm01.ril.com:8084
http-server.https.enabled.your-presto=true
http-server.https.port.your-presto=8084
http-server.https.keystore.path.your-presto=/home/presto/certs/keystoretemp.jks
http-server.https.keystore.key.your-presto=datta123
# almost same as presto coordinator url. If you use reverse proxy, specify it
#presto.redirect.server.your-presto=http://presto.coordinator:8080
# presto catalog name
catalog.your-presto=hive
# presto schema name
schema.your-presto=default
```

**JVM version** (`java -version`): oracle jdk"1.8.0_151"

**Server OS version** (`uname -a` if on a Unix-like system): centos 7.5 3.10.0-693.el7.x86_64

**Client OS version : centos 7.5 3.10.0-693.el7.x86_64

**Browser**: Firefox

**Description of the problem including expected versus actual behavior**: Unable to connect to secured presto

**Steps to reproduce**: changing coordinator url to https

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
        ... 71 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
```	

**Provide screenshots (if relevant)**:

**Comment by datta90** [comment]
solved above issue my importing the jks file to java truststore using below command 

keytool -trustcacerts -keystore cacerts -storepass password -importcert -alias alias.com -file /home/user/certs/keystoretemp.cer

and changing yanagishima-start.sh file. have added truststore path and password  

java $YANAGISHIMA_OPTS -Djavax.net.ssl.trustStore=/path/cacerts -Djavax.net.ssl.trustStorePassword=changeit -cp $CLASSPATH yanagishima.server.YanagishimaServer -conf $yanagishima_dir/conf $@ &

**Comment by hanson2021** [comment]
> solved above issue my importing the jks file to java truststore using below command
> 
> /opt/java/jdk1.8.0_151/bin/keytool -trustcacerts -keystore cacerts -storepass changeit -importcert -alias alias.com -file /home/presto/certs/keystoretemp.cer
> 
> and changing yanagishima-start.sh file. have added truststore path and password
> 
> java $YANAGISHIMA_OPTS -Djavax.net.ssl.trustStore=/opt/java/jdk1.8.0_151/jre/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit -cp $CLASSPATH yanagishima.server.YanagishimaServer -conf $yanagishima_dir/conf $@ &

I do as it  at yanashima-23.0, still failed.
Another question is the following args existed at the current version?
   http-server.https.enabled.your-presto=true
   http-server.https.port.your-presto=8084
   http-server.https.keystore.path.your-presto=/home/presto/certs/keystoretemp.jks
   http-server.https.keystore.key.your-presto=datta123

**Comment by datta90** [comment]
no these properties are irrevelant in yanagishima i had initially tried it with those properties but yanagishima does not understand them . so i have removed them from yanagishima
