### ISSUE TITLE
POST /hiveQueryStatus respond status code 500 java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by shawnzhu** [yanagishima/yanagishima#36]
**yanagishima version**: 14.0

**presto version**: 0.193

**Hive version**: 2.3.3

**conf/yanagishima.properties**:

```
jetty.port=8080
# 30 minutes. If presto query exceeds this time, yanagishima cancel the query.
presto.query.max-run-time-seconds=1800
# 1GB. If presto query result file size exceeds this value, yanagishima cancel the query.
presto.max-result-file-byte-size=1073741824
# you can specify freely. But you need to specify same name to presto.coordinator.server.[...] and presto.redirect.server.[...] and catalog.[...] and schema.[...]
presto.datasources=butane
auth.butane=false
# presto coordinator url
presto.coordinator.server.butane=http://abby-butane-presto-coordinator:8080
# presto catalog name
catalog.butane=hive
# presto schema name
schema.butane=default
# if query result exceeds this limit, to show rest of result is skipped
select.limit=500
# http header name for audit log
audit.http.header.name=some.auth.header
use.audit.http.header.name=false
# limit to convert from tsv to values query
to.values.query.limit=500
sql.query.engines=presto,hive

hive.jdbc.url.butane=jdbc:hive2://abby-butane-hive-metastore:10000/default?auth=noSasl
hive.jdbc.user.butane=scott
hive.jdbc.password.butane=tiger
hive.query.max-run-time-seconds=300
hive.query.max-run-time-seconds.butane=300
hive.datasources=butane
hive.disallowed.keywords.butane=insert
```

**JVM version** (`java -version`): 

```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Server OS version** (`uname -a` if on a Unix-like system): `Linux <xxx> 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 Linux`

**Client OS version**: macOS 10.13

**Browser**: Chrome version 68

**Description of the problem including expected versus actual behavior**:

When performing any Hive query, I expect query is executed with completion like any presto query (works very well).
Actual result: it keeps poping up error message in red alert box like `500 Please inform admin`. Although this very Hive query is sent to Hive server2 and completed (the Hive server2 log shows the query is executed successfully)

I found this request failed:

```
POST /hiveQueryStatus

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /hiveQueryStatus. Reason:
<pre>    java.util.NoSuchElementException: No value present</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.7.v20160115</a><hr/>
</body>
</html>
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Open `http://localhost:8080/#datasource=butane&engine=hive&tab=result` in browser
 2. Input query like `SHOW catalogs` then press button `Run`
 3. It shows progress notice like `Loading...`
 4. Then it keeps poping up alert box.

**Provide logs (if relevant)**:

```
2018/07/31 13:25:44.592 +0000 WARN [ServletHandler] [Yanagishima] /hiveQueryStatus
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at yanagishima.servlet.HiveQueryStatusServlet.doPost(HiveQueryStatusServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:38)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```
	
**Provide screenshots (if relevant)**:
<img width="1678" alt="screen shot 2018-07-31 at 09 40 45" src="https://user-images.githubusercontent.com/1059372/43463126-e222a7ac-94a5-11e8-8cb8-9364cd1e39e0.png">

**Comment by wyukawa** [comment]
Please specify yarn resource manager url because yanagishima uses the yarn rest api in order to track query status and kill.

https://hadoop.apache.org/docs/r2.7.3/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html

example
```
resource.manager.url.butane=http://resourcemanager:8088
```

Thanks

**Comment by shawnzhu** [comment]
@wyukawa Thanks for replying! That's interesting. I didn't use yarn at all since my Hive deployment is just a single node with hive-server2 and hive-metastore only.

I noticed that's why request like `/yarnJobList` failed too.

Question: is yarn is requirement of yanagishima when collecting Hive?
