### ISSUE TITLE
Mysql jdbc errors after no connecting to mysql for one day

### ISSUE THREAD

**Issue by darklore** [yanagishima/yanagishima#63]
Bug report

**yanagishima version**: 21.0

**presto version**: 318

**conf/yanagishima.properties**:
```
# yanagishima web port
jetty.port=8080

# backend RDMS
database.type=mysql
mysql.host=yanagishima-mysql
mysql.port=3306
mysql.database=yanagishima
mysql.user=yanagishima
mysql.password=xxxxxxxxxxxxxxxxxxx

# 30 minutes. If presto query exceeds this time, yanagishima cancel the query.
presto.query.max-run-time-seconds=1800

# 1GB. If presto query result file size exceeds this value, yanagishima cancel the query.
presto.max-result-file-byte-size=1073741824

# you can specify freely. But you need to specify same name to presto.coordinator.server.[...] and presto.redirect.server.[...] and catalog.[...] and schema.[...]
presto.datasources=your-presto
auth.your-presto=false

# presto coordinator url
presto.coordinator.server.your-presto=http://presto-coordinator:8080

# almost same as presto coordinator url. If you use reverse proxy, specify it
presto.redirect.server.your-presto=http://presto.xxxxxxxx.test:30080/ui

# presto catalog name
catalog.your-presto=hive

# presto schema name
schema.your-presto=default

# if query result exceeds this limit, to show rest of result is skipped
select.limit=500

# http header name for audit log
audit.http.header.name=some.auth.header
use.audit.http.header.name=false

# limit to convert from tsv to values query
to.values.query.limit=500

# authorization feature
check.datasource=false
hive.jdbc.url.your-hive=jdbc:hive2://hiveserver2:10000/default
hive.jdbc.user.your-hive=yanagishima
hive.jdbc.password.your-hive=yanagishima
hive.query.max-run-time-seconds=3600
hive.query.max-run-time-seconds.your-hive=3600
resource.manager.url.your-hive=http://resourcemanager:8088
sql.query.engines=presto,hive
hive.datasources=your-hive
hive.disallowed.keywords.your-hive=insert,drop

# 1GB. If hive query result file size exceeds this value, yanagishima cancel the query.
hive.max-result-file-byte-size=1073741824
hive.setup.query.path.your-hive=/usr/local/yanagishima/conf/hive_setup_query_your-hive
```

**JVM version** (`java -version`): openjdk version "11.0.3" 2019-04-16 LTS

**Server OS version** (`uname -a` if on a Unix-like system): Linux yanagishima-6d84dd6667-sl6q9 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**: Darwin w022581712182m.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

**Browser**: Chrome

**Description of the problem including expected versus actual behavior**:

When accessing yanagishima UI after haven't accessing the UI for one day,

Expected: Display UI without error popup.
Actual: Error popup "Please contact admin"  displays

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Deploy yanagishima server with mysql backend, and access the ui.
 2. Don't access the yanagishima ui for 1 day.
 3. Access the yanagishima ui

**Provide logs (if relevant)**:
Server log

```
2019/08/27 03:05:27.805 +0000 ERROR [RichSQLException] [Yanagishima] SQLException: No operations allowed after connection closed. SELECT engine, query_id, fetch_result_time_string, query_string FROM query WHERE engine='presto' and datasource='your-presto' and query_id IN () []                                                   [1/36290]
2019/08/27 03:05:27.806 +0000 WARN [ServletHandler] [Yanagishima] /query
me.geso.jdbcutils.UncheckedRichSQLException: SQL Exception: No operations allowed after connection closed.:SELECT engine, query_id, fetch_result_time_string, query_string FROM query WHERE engine='presto' and datasource='your-presto' and query_id IN ()([])
        at me.geso.tinyorm.TinyORM.prepareStatement(TinyORM.java:146)
        at me.geso.tinyorm.TinyORM.searchBySQL(TinyORM.java:294)
        at me.geso.tinyorm.TinyORM.searchBySQL(TinyORM.java:281)
        at yanagishima.servlet.QueryServlet.doPost(QueryServlet.java:142)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:38)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: me.geso.jdbcutils.RichSQLException: SQL Exception: No operations allowed after connection closed.:SELECT engine, query_id, fetch_result_time_string, query_string FROM query WHERE engine='presto' and datasource='your-presto' and query_id IN ()([])
        at me.geso.jdbcutils.UncheckedRichSQLException.<init>(UncheckedRichSQLException.java:13)
        ... 37 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4067)
        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4036)
        at me.geso.tinyorm.TinyORM.prepareStatement(TinyORM.java:140)
        ... 36 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 62,523,444 milliseconds ago.  The last packet sent successfully to the server was 62,523,444 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring an
d/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3751)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
        at me.geso.tinyorm.TinyORM.searchBySQL(TinyORM.java:296)
        ... 35 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3733)
        ... 41 more
```

**Provide screenshots (if relevant)**:
No screen shot. Sorry.

I think it will be resolved by adding "autoReconnect=true" to mysql url.
https://github.com/yanagishima/yanagishima/blob/487e70a3b5ac75a29b44d24647e41c96dbb0062f/src/main/java/yanagishima/provider/ConnectionProvider.java#L29

Thanks in advance.

**Comment by wyukawa** [comment]
Thank you for reporting.
Yes, this is the bug and it's related to my bad usage of Guice.
The workaround is to restart yanagishima server periodically(e.g. every 8 hours)

**Comment by kbill4345** [comment]
why not use a JDBC connection pool , the "autoReconnect=true" only avalibe in mysql4 or below
